[2025-03-06T04:54:27.773+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid19_etl.Extract manual__2025-03-06T04:54:07.016155+00:00 [queued]>
[2025-03-06T04:54:27.800+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid19_etl.Extract manual__2025-03-06T04:54:07.016155+00:00 [queued]>
[2025-03-06T04:54:27.801+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-03-06T04:54:27.801+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2025-03-06T04:54:27.802+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-03-06T04:54:27.843+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): Extract> on 2025-03-06 04:54:07.016155+00:00
[2025-03-06T04:54:27.858+0000] {standard_task_runner.py:55} INFO - Started process 3210 to run task
[2025-03-06T04:54:27.865+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'covid19_etl', 'Extract', 'manual__2025-03-06T04:54:07.016155+00:00', '--job-id', '742', '--raw', '--subdir', 'DAGS_FOLDER/covid19-etl.py', '--cfg-path', '/tmp/tmpn0aa2n1r']
[2025-03-06T04:54:27.874+0000] {standard_task_runner.py:83} INFO - Job 742: Subtask Extract
[2025-03-06T04:54:28.007+0000] {task_command.py:376} INFO - Running <TaskInstance: covid19_etl.Extract manual__2025-03-06T04:54:07.016155+00:00 [running]> on host e5021ab2b3c4
[2025-03-06T04:54:28.145+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sharaf
AIRFLOW_CTX_DAG_ID=covid19_etl
AIRFLOW_CTX_TASK_ID=Extract
AIRFLOW_CTX_EXECUTION_DATE=2025-03-06T04:54:07.016155+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-06T04:54:07.016155+00:00
[2025-03-06T04:54:28.164+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-06T04:54:28.237+0000] {covid19-etl.py:46} INFO - Extracting data from source
[2025-03-06T04:54:28.759+0000] {covid19-etl.py:63} ERROR - Error extracting data for 01-01-2020: HTTP Error 404: Not Found
[2025-03-06T04:54:29.948+0000] {covid19-etl.py:53} INFO - Extracted data for 01-01-2021
[2025-03-06T04:54:31.518+0000] {covid19-etl.py:53} INFO - Extracted data for 01-01-2022
[2025-03-06T04:54:32.690+0000] {covid19-etl.py:53} INFO - Extracted data for 01-01-2023
[2025-03-06T04:54:34.265+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-03-06T04:54:34.436+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=covid19_etl, task_id=Extract, execution_date=20250306T045407, start_date=20250306T045427, end_date=20250306T045434
[2025-03-06T04:54:34.798+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-03-06T04:54:35.039+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
